
plugins {
alias(libs.plugins.android.application) apply false
    alias(libs.plugins.jetbrains.kotlin.android) apply false
    alias(libs.plugins.android.library) apply false
}

ext {
    compileSdkVersion = 35
    targetSdkVersion = 35

    minSdk = 21
    versionCode = 22
    versionName = "0.2.2"
    xVersion = '1.2.0'
    hiddenApiBypass = '4.3'
}
