/**
 * IL2CPP Runtime Dumper - ImGui Overlay for MLBB
 * 
 * Injected .so that dumps IL2CPP metadata from live memory.
 * Based on MLBB-NUSANTARA architecture.
 * 
 * Instead of cheat features, this provides:
 * - ImGui menu with dump controls
 * - Real-time dump progress display
 * - IL2CPP class/method/field enumeration from live memory
 * - Output: dump.cs, il2cpp_methods.txt, il2cpp_classes.txt
 *
 * Enhanced by Panxcz & Freebuff
 */

#include "dumper.h"

// ==================== GLOBALS ====================

DumpState g_dumpState = {};
bool g_running = true;

// ==================== IL2CPP API RESOLUTION ====================

static int resolve_il2cpp_api() {
    void* handle = dlopen("libil2cpp.so", RTLD_NOW | RTLD_NOLOAD);
    if (!handle) {
        LOGE("dlopen libil2cpp.so failed: %s", dlerror());
        snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
            "Failed: libil2cpp.so not found");
        return -1;
    }

    #define RESOLVE(name, type) do { \
        g_dumpState.api_##name = (type)dlsym(handle, "il2cpp_" #name); \
    } while(0)

    RESOLVE(domain_get, fn_domain_get);
    RESOLVE(domain_get_assemblies, fn_domain_get_assemblies);
    RESOLVE(assembly_get_image, fn_assembly_get_image);
    RESOLVE(image_get_name, fn_image_get_name);
    RESOLVE(image_get_class_count, fn_image_get_class_count);
    RESOLVE(image_get_class, fn_image_get_class);
    RESOLVE(class_get_name, fn_class_get_name);
    RESOLVE(class_get_namespace, fn_class_get_namespace);
    RESOLVE(class_get_methods, fn_class_get_methods);
    RESOLVE(class_get_fields, fn_class_get_fields);
    RESOLVE(method_get_name, fn_method_get_name);
    RESOLVE(method_get_param_count, fn_method_get_param_count);
    RESOLVE(field_get_name, fn_field_get_name);
    RESOLVE(method_get_token, fn_method_get_token);

    #undef RESOLVE

    int resolved = 0;
    if (g_dumpState.api_domain_get) resolved++;
    if (g_dumpState.api_class_get_methods) resolved++;
    if (g_dumpState.api_class_get_fields) resolved++;
    if (g_dumpState.api_method_get_name) resolved++;
    if (g_dumpState.api_class_get_name) resolved++;

    LOGI("Resolved %d/14 IL2CPP API functions", resolved);
    dlclose(handle);

    if (!g_dumpState.api_domain_get || !g_dumpState.api_class_get_methods) {
        snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
            "Critical API missing (%d/14)", resolved);
        return -1;
    }

    snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
        "API ready (%d/14)", resolved);
    return 0;
}

// ==================== FIND LIB BASE ====================

static uintptr_t find_lib_base(const char* libName) {
    char path[256];
    snprintf(path, sizeof(path), "/proc/%d/maps", getpid());
    FILE* fp = fopen(path, "r");
    if (!fp) return 0;

    char line[512];
    uintptr_t base = 0;

    while (fgets(line, sizeof(line), fp)) {
        if (strstr(line, libName) && strstr(line, "r-xp")) {
            uintptr_t start, end;
            if (sscanf(line, "%lx-%lx", &start, &end) == 2) {
                base = start;
                g_dumpState.il2cppSize = end - start;
                break;
            }
        }
    }
    fclose(fp);
    return base;
}

// ==================== FILE OUTPUT ====================

static FILE* g_fp_dumpcs = nullptr;
static FILE* g_fp_methods = nullptr;
static FILE* g_fp_classes = nullptr;
static FILE* g_fp_offsets = nullptr;

static void write_dump_header() {
    if (!g_fp_dumpcs) return;
    
    fprintf(g_fp_dumpcs, "// ═══════ IL2CPP Runtime Dump (Native .so)\n");
    fprintf(g_fp_dumpcs, "// Generated by BlackBox Enhanced Dumper\n");
    fprintf(g_fp_dumpcs, "// Method pointers are REAL runtime addresses!\n");
    fprintf(g_fp_dumpcs, "// libil2cpp.so base: 0x%lx size: 0x%lx\n\n",
        g_dumpState.il2cppBase, g_dumpState.il2cppSize);
    fprintf(g_fp_dumpcs, "using System;\nusing System.Collections.Generic;\n\n");

    if (g_fp_offsets) {
        fprintf(g_fp_offsets, "// ═══════ IL2CPP Runtime Offsets ═══════\n");
        fprintf(g_fp_offsets, "// libil2cpp.so base: 0x%lx\n\n",
            g_dumpState.il2cppBase);
        fprintf(g_fp_offsets, "#define IL2CPP_BASE 0x%lx\n", g_dumpState.il2cppBase);
        fprintf(g_fp_offsets, "#define IL2CPP_SIZE 0x%lx\n\n", g_dumpState.il2cppSize);
    }
}

static void close_all_files() {
    if (g_fp_dumpcs) { fclose(g_fp_dumpcs); g_fp_dumpcs = nullptr; }
    if (g_fp_methods) { fclose(g_fp_methods); g_fp_methods = nullptr; }
    if (g_fp_classes) { fclose(g_fp_classes); g_fp_classes = nullptr; }
    if (g_fp_offsets) { fclose(g_fp_offsets); g_fp_offsets = nullptr; }
}

// ==================== IL2CPP DUMP ====================

static void dump_il2cpp() {
    if (!g_dumpState.api_domain_get) return;

    LOGI("=== Starting IL2CPP Runtime Dump ===");
    g_dumpState.dumping = true;
    g_dumpState.dumpComplete = false;
    g_dumpState.totalClasses = 0;
    g_dumpState.totalMethods = 0;
    g_dumpState.totalFields = 0;
    g_dumpState.progress = 0.0f;

    // Find libil2cpp.so base
    g_dumpState.il2cppBase = find_lib_base("libil2cpp.so");
    if (g_dumpState.il2cppBase == 0) {
        LOGE("libil2cpp.so not found in maps");
        snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
            "ERROR: libil2cpp.so not found");
        g_dumpState.dumping = false;
        return;
    }
    LOGI("libil2cpp.so base: 0x%lx", g_dumpState.il2cppBase);

    // Open output files
    char path[512];
    snprintf(path, sizeof(path), "%s/dump.cs", g_dumpState.outputPath);
    g_fp_dumpcs = fopen(path, "w");
    snprintf(path, sizeof(path), "%s/il2cpp_methods.txt", g_dumpState.outputPath);
    g_fp_methods = fopen(path, "w");
    snprintf(path, sizeof(path), "%s/il2cpp_classes.txt", g_dumpState.outputPath);
    g_fp_classes = fopen(path, "w");
    snprintf(path, sizeof(path), "%s/il2cpp_offsets.h", g_dumpState.outputPath);
    g_fp_offsets = fopen(path, "w");

    if (!g_fp_dumpcs) {
        LOGE("Cannot open output files");
        snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
            "ERROR: Cannot write to %s", g_dumpState.outputPath);
        g_dumpState.dumping = false;
        return;
    }

    write_dump_header();

    // Get domain
    const Il2CppDomain* domain = g_dumpState.api_domain_get();
    if (!domain) {
        LOGE("il2cpp_domain_get() returned NULL");
        snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
            "ERROR: domain_get() failed");
        close_all_files();
        g_dumpState.dumping = false;
        return;
    }

    // Get assemblies
    uint32_t assembly_count = 0;
    const void** assemblies = nullptr;
    if (g_dumpState.api_domain_get_assemblies) {
        assemblies = (const void**)g_dumpState.api_domain_get_assemblies(domain, &assembly_count);
    }

    g_dumpState.totalAssemblies = assembly_count;
    LOGI("Found %u assemblies", assembly_count);

    // Enumerate each assembly
    for (uint32_t i = 0; i < assembly_count && assemblies; i++) {
        const Il2CppAssembly* assembly = (const Il2CppAssembly*)assemblies[i];
        if (!assembly) continue;

        const Il2CppImage* image = g_dumpState.api_assembly_get_image ?
            g_dumpState.api_assembly_get_image(assembly) : nullptr;
        if (!image) continue;

        const char* image_name = g_dumpState.api_image_get_name ?
            g_dumpState.api_image_get_name(image) : "Unknown";
        if (!image_name) image_name = "Unknown";

        LOGI("Assembly[%u]: %s", i, image_name);

        if (g_fp_dumpcs) {
            fprintf(g_fp_dumpcs, "\n// ═══════ Assembly: %s ═══════\n\n", image_name);
        }

        // Enumerate classes
        uint32_t class_count = g_dumpState.api_image_get_class_count ?
            g_dumpState.api_image_get_class_count(image) : 0;

        for (uint32_t j = 0; j < class_count; j++) {
            const Il2CppClass* klass = g_dumpState.api_image_get_class ?
                g_dumpState.api_image_get_class(image, j) : nullptr;
            if (!klass) continue;

            const char* class_name = g_dumpState.api_class_get_name ?
                g_dumpState.api_class_get_name(klass) : nullptr;
            const char* ns = g_dumpState.api_class_get_namespace ?
                g_dumpState.api_class_get_namespace(klass) : "";
            if (!class_name || !class_name[0]) continue;

            g_dumpState.totalClasses++;

            char full_name[512];
            if (ns && ns[0]) {
                snprintf(full_name, sizeof(full_name), "%s.%s", ns, class_name);
            } else {
                snprintf(full_name, sizeof(full_name), "%s", class_name);
            }

            // Classes list
            if (g_fp_classes) {
                fprintf(g_fp_classes, "[%d] %s (from %s)\n",
                    g_dumpState.totalClasses, full_name, image_name);
            }

            // dump.cs - class definition
            if (g_fp_dumpcs) {
                fprintf(g_fp_dumpcs, "// Image: %s\n", image_name);
                fprintf(g_fp_dumpcs, "public class %s\n{\n", class_name);
            }

            // Fields
            if (g_dumpState.api_class_get_fields && g_fp_dumpcs) {
                void* iter = nullptr;
                const Il2CppFieldInfo_* field;
                while ((field = g_dumpState.api_class_get_fields(klass, &iter)) != nullptr) {
                    const char* fname = g_dumpState.api_field_get_name ?
                        g_dumpState.api_field_get_name(field) : nullptr;
                    if (!fname) continue;

                    g_dumpState.totalFields++;

                    // Read offset from struct (offset is at byte offset 32 on arm64)
                    int32_t field_offset = 0;
                    const char* raw = (const char*)field;
                    memcpy(&field_offset, raw + 32, sizeof(int32_t));

                    fprintf(g_fp_dumpcs, "    public object %s; // 0x%04x\n",
                        fname, field_offset);

                    if (g_fp_offsets) {
                        fprintf(g_fp_offsets, "FIELD %s::%s offset=0x%x\n",
                            full_name, fname, field_offset);
                    }
                }
            }

            fprintf(g_fp_dumpcs, "\n");

            // Methods with REAL RUNTIME ADDRESSES
            if (g_dumpState.api_class_get_methods && g_fp_dumpcs) {
                void* iter = nullptr;
                const Il2CppMethodInfo_* method;
                while ((method = g_dumpState.api_class_get_methods(klass, &iter)) != nullptr) {
                    const char* mname = g_dumpState.api_method_get_name ?
                        g_dumpState.api_method_get_name(method) : nullptr;
                    if (!mname) continue;

                    g_dumpState.totalMethods++;

                    // REAL method pointer from live memory!
                    void* method_ptr = method->method_pointer;
                    uintptr_t rva = 0;
                    if (method_ptr && g_dumpState.il2cppBase) {
                        rva = (uintptr_t)method_ptr - g_dumpState.il2cppBase;
                    }

                    int param_count = g_dumpState.api_method_get_param_count ?
                        g_dumpState.api_method_get_param_count(method) : 0;

                    uint32_t token = g_dumpState.api_method_get_token ?
                        g_dumpState.api_method_get_token(method) : 0;

                    fprintf(g_fp_dumpcs,
                        "    public extern void %s(); // RVA: 0x%08x ptr: %p token: 0x%x params: %d\n",
                        mname, (uint32_t)rva, method_ptr, token, param_count);

                    if (g_fp_methods) {
                        fprintf(g_fp_methods, "  %s.%s rva=0x%08x ptr=%p token=0x%x params=%d\n",
                            class_name, mname, (uint32_t)rva, method_ptr, token, param_count);
                    }
                }
            }

            if (g_fp_dumpcs) {
                fprintf(g_fp_dumpcs, "}\n\n");
            }

            // Update progress
            float progress = (float)g_dumpState.totalClasses / 
                ((float)class_count * (float)assembly_count) * 100.0f;
            g_dumpState.progress = progress > 100.0f ? 100.0f : progress;

            // Update status
            snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
                "Dumping... %d classes, %d methods",
                g_dumpState.totalClasses, g_dumpState.totalMethods);
        }
    }

    // Write summary
    if (g_fp_dumpcs) {
        fprintf(g_fp_dumpcs, "\n// ═══════ DUMP SUMMARY ═══════\n");
        fprintf(g_fp_dumpcs, "// Total classes: %d\n", g_dumpState.totalClasses);
        fprintf(g_fp_dumpcs, "// Total methods: %d\n", g_dumpState.totalMethods);
        fprintf(g_fp_dumpcs, "// Total fields: %d\n", g_dumpState.totalFields);
        fprintf(g_fp_dumpcs, "// libil2cpp base: 0x%lx\n", g_dumpState.il2cppBase);
        fprintf(g_fp_dumpcs, "// Method pointers are absolute runtime addresses\n");
        fprintf(g_fp_dumpcs, "// RVA = ptr - libil2cpp_base\n");
    }

    // Write maps info
    char maps_path[512];
    snprintf(maps_path, sizeof(maps_path), "%s/maps.txt", g_dumpState.outputPath);
    FILE* maps_fp = fopen(maps_path, "w");
    if (maps_fp) {
        FILE* maps = fopen("/proc/self/maps", "r");
        if (maps) {
            char line[512];
            while (fgets(line, sizeof(line), maps)) {
                if (strstr(line, "libil2cpp.so")) {
                    fprintf(maps_fp, "%s", line);
                }
            }
            fclose(maps);
        }
        fclose(maps_fp);
    }

    close_all_files();

    g_dumpState.progress = 100.0f;
    g_dumpState.dumpComplete = true;
    g_dumpState.dumping = false;
    snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
        "DONE! %d classes, %d methods, %d fields",
        g_dumpState.totalClasses, g_dumpState.totalMethods, g_dumpState.totalFields);

    LOGI("=== DUMP COMPLETE ===");
    LOGI("  Classes: %d", g_dumpState.totalClasses);
    LOGI("  Methods: %d", g_dumpState.totalMethods);
    LOGI("  Fields:  %d", g_dumpState.totalFields);
}

// ==================== DUMP THREAD ====================

static void* dump_thread_func(void* arg) {
    // Wait a bit for IL2CPP to initialize
    sleep(2);
    
    snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
        "Waiting for IL2CPP to initialize...");
    
    // Try to find libil2cpp.so
    int retries = 0;
    while (g_dumpState.il2cppBase == 0 && retries < 30) {
        g_dumpState.il2cppBase = find_lib_base("libil2cpp.so");
        if (g_dumpState.il2cppBase == 0) {
            sleep(1);
            retries++;
        }
    }

    if (g_dumpState.il2cppBase == 0) {
        snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
            "ERROR: libil2cpp.so not found after %d retries", retries);
        return nullptr;
    }

    snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg),
        "libil2cpp.so found at 0x%lx, resolving API...",
        g_dumpState.il2cppBase);

    // Resolve API
    if (resolve_il2cpp_api() != 0) {
        return nullptr;
    }

    // Run the dump
    dump_il2cpp();

    return nullptr;
}

// ==================== START DUMP ====================

extern "C" __attribute__((visibility("default")))
void start_il2cpp_dump(const char* outputDir) {
    if (g_dumpState.dumping) {
        LOGI("Dump already in progress");
        return;
    }

    snprintf(g_dumpState.outputPath, sizeof(g_dumpState.outputPath), "%s", outputDir);
    snprintf(g_dumpState.statusMsg, sizeof(g_dumpState.statusMsg), "Starting dump...");

    // Create output directory
    mkdir("/storage/emulated/0/Download/black/dump", 0777);
    mkdir(outputDir, 0777);

    // Start dump thread
    pthread_t thread;
    pthread_create(&thread, nullptr, dump_thread_func, nullptr);
    pthread_detach(thread);
}

extern "C" __attribute__((visibility("default")))
const char* get_dump_status() {
    return g_dumpState.statusMsg;
}

extern "C" __attribute__((visibility("default")))
float get_dump_progress() {
    return g_dumpState.progress;
}

extern "C" __attribute__((visibility("default")))
bool is_dump_complete() {
    return g_dumpState.dumpComplete;
}

extern "C" __attribute__((visibility("default")))
uintptr_t get_il2cpp_base() {
    if (g_dumpState.il2cppBase == 0) {
        g_dumpState.il2cppBase = find_lib_base("libil2cpp.so");
    }
    return g_dumpState.il2cppBase;
}
